import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Nav from './auth/Nav'
import { Roboto } from 'next/font/google'

const robot = Roboto({
  subsets: ['latin'],
  weight: ["400","700"],
  variable: "--font-roboto",
})

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Nav />
      <body className={`${inter.className} mx-4 md:mx-48 xl:mx-9`}>{children}</body>
    </html>
  )
}
